### ISSUE TITLE
show a message when there is nothing to record

### ISSUE THREAD

**Issue by mozillakab** [mozilla/common-voice#2478]
I suggest to show a message inviting the user to visit Sentence Collector when there is nothing to record (or validate other recordings).

![2019-12-13 19_41_31-Common Voice](https://user-images.githubusercontent.com/7033740/70823944-5e96a700-1de1-11ea-956b-7c8b17bfc3aa.jpg)

**Comment by SelyanKab** [comment]
Good idea, many people think it's a bug, when it's missing sentences.

**Comment by Rolikasi** [comment]
@MichaelKohler hello. Can I work on this issue? It seems like a good first issue

**Comment by MichaelKohler** [comment]
@Rolikasi thanks for your interest. Let's wait until there is an agreement that this is still wanted and an agreed design. Otherwise we risk that you work on it and then it turns out to not be wanted anymore.

@mbransn is this still wanted, and how should this look?

**Comment by mbransn** [comment]
Hi both, this is something we've actually pulled into our current internal sprint -- @phirework do you prefer help on this or already in motion on your end?

**Comment by phirework** [comment]
Hey all, I've got this one in hand :)

**Comment by shakti97** [comment]
hi @phirework are you still working on this or its already done, If already done , can we close this issue and if not may I work on this issue

**Comment by mbransn** [comment]
@shakti97 this is already assigned and will be closed when the work is merged to production. Thanks!

**Comment by phirework** [comment]
This has been available on production for a few months, closing the issue!
