### ISSUE TITLE
Submit report button missing in Brave browser for Android

### ISSUE THREAD

**Issue by bitplane** [mozilla/common-voice#2560]
# browser details

* Android 9
 * Brave 1.5.4 / Chromium 79.0.3945.136

# steps

1. Go to https://voice.mozilla.org/en/listen
2. Click "report »»" button
3. Select a reason and scroll to bottom of page

## expected result
There should be a submit button at the bottom of the page

## actual result
The submit button is missing

# screenshot

![Screenshot_20200209-195655](https://user-images.githubusercontent.com/273059/74109017-a0409580-4b77-11ea-9040-ccf7e02ad5b8.jpg)

**Comment by bitplane** [comment]
Turning off "fingerprint protection" makes this button show up again. So it must be that the button being created is suspicious and gets blocked.

**Comment by dag7dev** [comment]
This has been fixed in Brave 1.16.70 Chromium 86.0.4240.111 Android 10 with fingerprint protection.
For "listening to recordings" the issue doesn't apply. For "sending recordings" you just need to scroll down once more to let the button be loaded.
