### ISSUE TITLE
No Need for Search Button

### ISSUE THREAD

**Issue by shakti97** [mozilla/common-voice#2640]
## Description
We are searching and showing result as soon as the user change the search input on FAQ, so there will be no use of search button on the right of the search box, we might just use that for the ui, but we can remove the handler from the search button

## Current Behaviour
We are showing search result as soon as the user start typing so there will be no need of search button, but user can click on the search button and search button doesn't do anything because the result is already showing

## Expected Behaviour
We should only use that search icon in ui and remove handler from the button

## Additional Information
I would like to work on it

**Comment by shakti97** [comment]
Should I start working on this issue @MichaelKohler

**Comment by phirework** [comment]
As discussed in PR, we are keeping the redundant action.
