### ISSUE TITLE
Send button hidden on ipad 11" portrait

### ISSUE THREAD

**Issue by nukeador** [mozilla/common-voice#2739]
Recording in Spanish on an ipad 11" 5th gen portrait mode, the send button is hidden from the view, you need to scroll to see it.

![imagen](https://user-images.githubusercontent.com/531906/82831229-24fdb800-9eb8-11ea-89e8-a60e241f76e4.png)

**Comment by bacharakis** [comment]
Hi @nukeador , can you please confirm whether this is not fixed with the recently launched version of Common Voice?
Thank you
-Christos
