### ISSUE TITLE
Log time scale on "Hours Recorded/Hours Validated" makes it difficult to see progress

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/common-voice#2741]
Because of the time scale it makes it looks though the rate of progress is always slowing down. Further, because each data point seems represents a different amount of time from the previous it's difficult to draw any intuitive conclusions from the looking at the graph.

**Comment by Maltimore** [comment]
I would like to bump this issue. It has been bugging me too for a long while now. @bacharakis I don't see why it needs triage?

**Comment by phirework** [comment]
Will be fixed in next release.

**Comment by jrmuizel** [comment]
It doesn't look like this is fixed yet. When is the next release?

**Comment by phirework** [comment]
The graph currently shows the past year in a linear scale, with 3 months between each data point, as opposed to 1 day/week/month etc.

**Comment by jrmuizel** [comment]
Ah, you're right. Sorry about that.
