### ISSUE TITLE
Tablet Demo - Benefits Scroll

### ISSUE THREAD

**Issue by grailean** [mozilla/common-voice#2839]
**Describe the bug**
The benefit should change on scroll, it does not need to be pressed to activate

**Expected behavior**
We expect the user to scroll and the image to be changed for each item that is highlighted. 

**Screenshots**
https://www.dropbox.com/s/t8s9gvf5d61c7fv/Screenshot%202020-07-20%2014.03.12.png?dl=0
**Desktop or Mobile (please complete the following information):**

**Comment by phirework** [comment]
@mbransn Can I get you to weigh in on this issue? The homepage behaviour for this same element is to change the image on click, not scroll. I'm not sure an on-scroll change makes sense when all of the content is so short and multiple things are visible at the same time, the eye-level of the reader will not necessarily match the position of the scroll.

**Comment by mbransn** [comment]
Thanks for the flag, I'm good with maintaining a tap / click interaction -- esp. as our primary use case is tablet for this. Going to close this out.
