### ISSUE TITLE
404 page getting triggered after routing to listen page after logging in

### ISSUE THREAD

**Issue by phirework** [mozilla/common-voice#2856]
Report in Element from a contributor who doesn't have a Github account: 

**Describe the bug**
When I want to validate and click the button on the Esperanto main page, I get a 404: https://commonvoice.mozilla.org/eo/404 - when I go back in browser history one time I am on the validation page.

**To Reproduce**
Video: https://www.thschuetz.de/temp/commonvoice404.mp4

**Expected behavior**
Should go to the /listen page, not 404 

**Desktop or Mobile (please complete the following information):**
 - OS: Linux
 - Browser Firefox

**Additional context**
Started after the last release

--- 

Notes from Jenny - I was able to reproduce this in languages other than English

**Comment by nukeador** [comment]
Going to https://commonvoice.mozilla.org/es/languages and click any language contribute link (except from Spanish) returns a 404.

**Comment by bacharakis** [comment]
Just checked and verified that indeed it doesn't work in all languages except English. Spanish doesn't work either @nukeador .
The interesting part, is that when I get the 404, if I click the back button in my browser, I get the proper localized listen page.

STR: 

1. Go to [languages page](https://commonvoice.mozilla.org/en/languages)
2. Pick a language and click the contribute button -> You will get a 404 page.
3. Click the back button -> you will get the proper page!

**Comment by nukeador** [comment]
More 404s that might be related with this issue?

https://discourse.mozilla.org/t/404-on-sso-login/65288

**Comment by phirework** [comment]
This was fixed at some point in the last few rounds of UX updates.
