### ISSUE TITLE
Mozilla/commom-voice/local

### ISSUE THREAD

**Issue by nissa1992** [mozilla/common-voice#2878]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ftyers** [comment]
Hi there, you might be better trying this on Discourse, and take a look at https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530. The GitHub issues aren't for these kinds of questions.

**Comment by ftyers** [comment]
Also, Indonesian is already on Common Voice, you can just go [here](https://commonvoice.mozilla.org/id).

**Comment by nissa1992** [comment]
seseorang mengikuti saya and remote my macbook need SLA PDF 2014 after im closed my mac maybe its angry!!!!
