### ISSUE TITLE
Kurdish: Migrate data from `ku` to `ckb`

### ISSUE THREAD

**Issue by peiying2** [mozilla/common-voice#2886]
Kurdish: fix the mismatch of Kurdish in Pontoon and Common Voice repo
- Kurdish expressed as `ku` per CLDR  is written in Latin script, and written from Left to Right. This is the current configuration in Pontoon
- The contribution from the community is in Arabic and it is RTL.
- Locale code `ckb`, or Central Kurdish, is the correct language name and locale code to represent the data in CV repo.
- `ckb` locale is established in Pontoon, with other active projects. CV will be an added project to that community/language.

**Steps**:
Dev:
- CV creates an `ckb` folder at repo
- Move `ku` repo content to `ckb` repo and confirm the move is a success
- Remove `ku` in repo

Pontoon (l10n):
- Pontoon dev migrates the data to `ckb` (this includes contributors histories)
- L10n PM confirms the update and closes this issue.

**Comment by phirework** [comment]
@MichaelKohler Does this also need to be manually migrated on SC?

**Comment by MichaelKohler** [comment]
Yep.

**Comment by ftyers** [comment]
There is now [a request](https://groups.google.com/g/mozilla.dev.l10n.new-locales/c/psQ7EKqIYTM) on the l10n list to enable Kurmanji Kurdish.

**Comment by jwtiyar** [comment]
please guys, Kmr should be activated not ku as he mentioned , because
according to iso-693-3, Kurmanji is kmr not ku.


Best Regards

**Comment by peiying2** [comment]
Let's not mix up the requests here. The opening of `kmr` for Kurmanji is a separate issue. Common Voice repo would open up to this new locale once the project reaches certain level of completion.

**Comment by ftyers** [comment]
@jwtiyar it's open as `kmr`: https://pontoon.mozilla.org/kmr/ -- Thanks for your input!

**Comment by jwtiyar** [comment]
Thank you dear Tyres.

**Comment by roxima** [comment]
@peiying2 Does this migration include sentence collector data or we need to open another issue?

**Comment by peiying2** [comment]
> @peiying2 Does this migration include sentence collector data or we need to open another issue?

Sorry I missed this one. The Data collection happens outside of Pontoon, so Common Voice team needs to be fully involved in this. 

@phirework should the team create a new issue for this request?

**Comment by phirework** [comment]
The sentence collector data that is currently part of the CV corpus has also been migrated, yep. https://github.com/mozilla/common-voice/pull/2895

The Sentence Collector tool itself will also need to update its language code, I don't know if @MichaelKohler wants to just add another mapping to the exports process or actually migrate it in the DB? Either way, the issue would need to be filed in https://github.com/Common-Voice/sentence-collector/

**Comment by MichaelKohler** [comment]
I don't need an extra issue. I'll just add another mapping for now, and then will do a clean migration on the new data structure. Will report back here when done.

**Comment by phirework** [comment]
Perfect, thank you!

**Comment by roxima** [comment]
@MichaelKohler Nice, looking forward to it.

**Comment by MichaelKohler** [comment]
Sentence Collector is done as well:

* Mapping: https://github.com/Common-Voice/sentence-collector/pull/327
* Verified Export: https://github.com/mozilla/common-voice/pull/2900/files#diff-b5f97e8dd8701d6e24f1ea5441723483
* Follow up task (only cleanup, doesn't need to be tracked): https://github.com/Common-Voice/sentence-collector/issues/326

**Comment by peiying2** [comment]
This issue is completely resolved. Thanks everyone!
