### ISSUE TITLE
Training DeepSpeech model with World English Bible Audio Data.

### ISSUE THREAD

**Issue by jasser94** [mozilla/common-voice#2887]
When I try to predict Bible verses via English deepspeech model i always getting wrong words especially the specific ones related to bible vocabulary.

Regarding that i have an open source data of World English Bible audios i would like to suggest to train the deepspeech model with it for better and correct prediction result.

Since i don't have the necessary environment to train the model in normal conditions, an assistance from mozilla support team will be very welcome.

**Comment by phirework** [comment]
Hello! Common Voice is a platform for collecting voice data only, and for any issues related to the STT model you're looking for the [DeepSpeech](https://github.com/mozilla/DeepSpeech) repo. Unfortunately, as both Common Voice and Deep Speech have [very limited support](https://discourse.mozilla.org/t/future-of-deepspeech-stt-after-recent-changes-at-mozilla/66191) inside of Mozilla right now, you'll probably have better luck asking for help on [the Discourse forum](https://discourse.mozilla.org/c/mozilla-voice-stt/247).
