### ISSUE TITLE
Remove glitchy/clicky recordings

### ISSUE THREAD

**Issue by caseybasichis** [mozilla/common-voice#2912]
Recorded 200 wavs on my iPhone.  The recordings seem to have pops and glitches.  (bug in the web app?)

Created an account and recorded 300 more waves on my desktop, which sound good.

Going back to the phone and logging in for the first time, added the 200 glitchy wave files to the account without asking.

How can I delete the 200 contributed from my phone or otherwise review them?

I am worried I am messing up my account and validity of my contribution by introducing so many broken files.

In QCing other people recording I occasionally encounter other people who also have these glitchy recordings (usually the same person) though the majority are ok.

What can I do?

**Comment by ftyers** [comment]
Hi! Thanks for getting in contact and for your feedback. This looks more like a support request, so the appropriate avenue is probably [Discourse](https://discourse.mozilla.org/c/voice/239), you might get a better response there. About your question, in general problems in the recording quality, if the sentence is still audible, is not a problem for speech recognition, in fact it is desirable, we want to be able to do speech recognition from all kinds of different devices, as well as from all kinds of different voices and accents.

**Comment by phirework** [comment]
Hi, there's no easy way to remove only some files from an account so we generally don't do this. If the audio files are genuinely broken, then the community validation process will mark them as invalid for the purposes of ASR. 

Why are you concerned about "messing up your account"? We don't demote your contributions if you've had a lot of invalidated clips or anything like that, and there's no way for you or anyone else to search for just the clips you contributed, so I wouldn't worry too much about it. 

Thanks for the bug report on iOS, we know there are some issues with our polyfill that we're still ironing out.

**Comment by caseybasichis** [comment]
> Why are you concerned about "messing up your account"?

Individual dev's may tend to filter the dataset for their own purposes -- eliminating speakers with noisy or glitchy recordings.

I understand that quality diversity can be important in some settings, but I'd like my contribution to be broadly applicable.

I've given up on Common Voice for now though.  I encountered quite a few issues that have turned me off of it -- the inability to download my own clips most importantly.
