### ISSUE TITLE
Add Basaa language for collection

### ISSUE THREAD

**Issue by ftyers** [mozilla/common-voice#2918]
Could you please add collection for Basaa (ISO-639: `bas`) ? Also tracking this through a [Discourse post](https://discourse.mozilla.org/t/turning-on-basa-bas/69147?u=ngue_um_emmanuel).

**Comment by MichaelKohler** [comment]
Happy to add this to the Sentence Collector once it's in Pontoon.

**Comment by ftyers** [comment]
Here is the information for Pontoon from Discourse:
```

    What Mozilla product are you hoping to localise? Keep in mind that
    Firefox desktop is a rather large project which can potentially take a long
    time for a full localisation to ship.

Common Voice

    Which language code should be used? (ISO-639-1, ISO-639-3, country code).

bas

    How many plural forms are in the language? To give an example,
    how would you translate the following phrases:

        0 rocks, tɔ̀ ŋgɔ̀k tɔ̀ yàda
        1 rock, ŋgɔ̀k yàda
        2 rocks, màŋgɔ̀k mâ
        3 rocks, màŋgɔ̀k maa
        4 rocks, màŋgɔ̀k manâ
        5 rocks, màŋgɔ̀k mátân
        10 rocks, jǒm li ŋgɔ̂k
        20 rocks, mòm mâ ma maŋgɔ̀k
        100 rocks, mbogôl màŋgɔ̀k
        1000 rocks, hìkóó hi máŋgɔ̀k
        I see 0 rocks on the ground,mɛ̀ ńtɛ̄hɛ̄ ɓe mɛ̂ tɔ̀ ŋgɔ̀k yàdá hīsī
        I see 1 rock on the ground,mɛ̀ ńtɛ̄hɛ̄ ŋgɔ̀k yàda hīsī
        I see 10 rock on the ground,mɛ̀ ńtɛ̄hɛ̄ jom li maŋgɔ̀k hīsī
        I see rocks on the ground,mɛ̀ ńtɛ̄hɛ̄ maŋgɔ̀k hīsī

    Are you hoping to localise alone or do you have friends that will join
    you? For sustainability of the localisation (because we’re always releasing
    new versions of Firefox products that will need localising), we’d prefer to
    only ship new locales that have more than one person sustaining them.

There are many people in the community who will participate. Basa is a community of approximately 300 000 speakers.
```

**Comment by ftyers** [comment]
@mbransn @phirework Hi both, could you let us know if anything here is missing? Thanks!

**Comment by peiying2** [comment]
Thank you @ftyers for putting in the request. I have a couple of questions:
- Singular and plural: I notice that 0, 1, and 10 share the same word while the rest use a different word for rock. Is there another language the person knows that is similar to Basaa in terms the singular/plural rules?
- Need a person who is going to work in Pontoon, making contribution directly there. The person needs to create an account so I can assign him/her as the community manager and share other some basic docs to get it started.

**Comment by ftyers** [comment]
It is like any of the Bantu languages (isiZulu, Kiswahili etc.). 

The translations all have the same word for "rock" *ŋgɔ̀k*, but the plural is a prefix, e.g. *maŋgɔ̀k*. It is just that in some cases the number comes before and in others after. The translation for "zero" uses something like "not any at all" instead of the numeral "zero".

The user in Pontoon should be Emmanuel Ngue Um.

**Comment by peiying2** [comment]
The language and the Common Voice project are added in Pontoon: https://pontoon.mozilla.org/bas/. We now need Emmanuel create an account in Pontoon so I can add him to the project and reach out to him on tool and process.

**Comment by ftyers** [comment]
Fantastic thanks @peiying2 ! I'll get in contact and let him know.

**Comment by ftyers** [comment]
@MichaelKohler could you enable it in sentencecollector ? It's in Pontoon now: https://pontoon.mozilla.org/bas/ Thanks!

**Comment by MichaelKohler** [comment]
@ftyers will do, forgot to ask before: what is the correct native name (as we show both English and the native language name)?

**Comment by ftyers** [comment]
@MichaelKohler Ɓàsàa should work

**Comment by MichaelKohler** [comment]
@ftyers done

**Comment by ftyers** [comment]
@peiying2 Emmanuel has created an account, could you add him as a manager? https://pontoon.mozilla.org/bas/common-voice/contributors/ Thanks! :)

**Comment by peiying2** [comment]
Done! I have approved the strings he has submitted. I will follow up with instructions for using Pontoon, CV project info and community guidelines, :). Feel free to close this issue if nothing else is needed.

**Comment by ftyers** [comment]
Ltgm!

**Comment by ftyers** [comment]
Oops, one last thing, could we get `bas` onto https://commonvoice.allizom.org/bas ? Thanks!

**Comment by phirework** [comment]
Hey folks, added this to the Dev server, and it'll meander its way to production with the next release. You can't really tell right now since it's barely localized, but if you look at https://dev.commonvoice.allizom.org/bas/languages you'll see Basaa in the list of in-progress languages. Thanks for the coordination both!
