### ISSUE TITLE
Cannot contribute to https://commonvoice.mozilla.org with Firefox 82

### ISSUE THREAD

**Issue by monperrus** [mozilla/common-voice#2921]
**To Reproduce**

Open https://commonvoice.mozilla.org with Firefox 82

**Expected behavior**

I can upload or validate examples

**Actual behavior**

Message: `We’re sorry, your platform is not currently supported.`

**Comment by ubaidisaev** [comment]
Please provide more information.  I don't have such problem.
Window 10
Firefox 82.0 (64-bit)

**Comment by monperrus** [comment]
I'm using  Firefox 82.0 (64-bit) on Ubuntu, with some plugins.

**Comment by phirework** [comment]
Is this still an issue?

**Comment by monperrus** [comment]
Just tried with FF 84.0 on Linux, it works now. Thanks.
