### ISSUE TITLE
Hebrew landing page signup-button covered

### ISSUE THREAD

**Issue by cptwunderlich** [mozilla/common-voice#2923]
On the Hebrew landing page, for not-logged-in users, the "signup"-Button in the 'register-section' is hidden by the wave image.
With the default left-to-right layout, the text and button are on the left and the robot and "waves"-background on the right.
The right-to-left layout only switches sides for the robot and text/button, but not the "waves". Their button's z-index seems to be lower than the waves though.

**To Reproduce**
1. Open Private Tab
2. Visit https://commonvoice.mozilla.org/he
3. Scroll down

**Expected behavior**
The button should not be over the wave. Alternatively the waves should be mirrored to the left (analogous to the LTR layout).

**Screenshots**
https://imgur.com/a/nh2Dapp

**Desktop**
 - OS: Ubuntu 20.04
 - Firefox
 - Version 82

**Note**:
Adding 'style="z-index: 1"' to the button fixes it. But I'm not familiar with React, so I can't really offer a patch.

**Comment by kshitij86** [comment]
@cptwunderlich I wasn't able to test this on my PC, it looks nothing like the one in the screenshot. Could this be due to orientation inversion due to Hebrew?

**Comment by cptwunderlich** [comment]
Huh. It got fixed!
It was indeed about the right-to-left layout of Hebrew. The Waves were supposed to be on the "opposite side" of the button. Alternatively, putting them in the background would have worked.
