### ISSUE TITLE
Please allow sentences to be recorded by more than one person

### ISSUE THREAD

**Issue by ftyers** [mozilla/common-voice#2948]
This is related to:
https://discourse.mozilla.org/t/single-sentence-record-limit-feature-release/62198/
https://discourse.mozilla.org/t/turn-off-the-thing-where-users-cant-record-all-the-sentences-for-chuvash/65339

I realise that the Common Voice team probably doesn't have time to implement this on a per-language basis, but this is very painful for communities trying to get off the ground and so could just be turned off at least until something less damaging can be implemented.

For the purposes of ASR, it doesn't matter that much as a postprocess can remove any duplicates, if the particular system being trained requires that. It is by no means proven that non-inclusion of duplicates is better than including them.

**Comment by irvin** [comment]
Hong Kong Cantonese locale (zh-hk) also faced this limit, and it's become a big problem due to recent promotion which onboard thousand new contributors, and also blocks the planned cooperation with the local school to bring local students to Common Voice.

**Comment by phirework** [comment]
The fix (#2955) is now on production, let me know if you experience additional issues. Thanks for all the feedback folks.
