### ISSUE TITLE
Listen not working on cy

### ISSUE THREAD

**Issue by rprys** [mozilla/common-voice#2961]
We're at 122 hour recorded and 94 hours verified, so there shouldn't be a problem with verifying more clips.

https://commonvoice.mozilla.org/cy/listen

We've got a big push starting on 28/12 so we need this to work! :-)

**Comment by phirework** [comment]
That link works for me, what specific error are you experiencing?

**Comment by rprys** [comment]
The link stopped working c. 14:00pm GMT until I tried it again c. 20:00pm yesterday. The page was saying that there were no further clips to be verified. It's working again now now,and offering clips to be verified.
Thanks
