### ISSUE TITLE
Kazakh is ready to be launched on commonvoice.mozilla.org

### ISSUE THREAD

**Issue by IlnarSelimcan** [mozilla/common-voice#2974]
Hi,

we've finished translating CV's interface into Kazakh on Pontoon, and recently collected and validated over 5000 sentences on the sentence collector tool as well.

I assume that launching a new language on Common Voice requires manual intervention, hence this issue.

Please let me know if there is anything else I can do to launch Kazakh on Common Voice.

**Comment by phirework** [comment]
This is great news! It'll launch with the next Common Voice site release, which will be next Tuesday. I'll check back in here when that goes live.

**Comment by ftyers** [comment]
It's launched: https://commonvoice.mozilla.org/kk This can be closed, thanks @phirework ! :)
