### ISSUE TITLE
Basaa is ready to be launched on commonvoice.mozilla.org

### ISSUE THREAD

**Issue by ftyers** [mozilla/common-voice#2980]
Hi there, Basaa now has >5k sentences and 100% localisation and is ready to be launched! :)

**Comment by phirework** [comment]
It's up on staging! Will probably go live tomorrow :) https://commonvoice.allizom.org/bas

**Comment by ftyers** [comment]
https://commonvoice.mozilla.org/bas ! Yes!! :D Thanks! ^__^
